### ISSUE TITLE
How to access button A and B?

### ISSUE THREAD

**Issue by colombod** [DFRobot/pxt-gamePad#1]
Cannot find out to use the white A and B button, they are not clearly exposed by the library

**Comment by cstratton** [comment]
Buttons A and B on the gamepad merely duplicate buttons A and B on the bit itself, so you use the ordinary microbit input blocks to read them, rather than anything from the library.

I guess they're there because the bigger buttons are easier to push and avoid pushing down on the buttons on the bit while it's in the socket.
